# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint

on:
  workflow_call:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics

  pass_label:
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ success() }}
    steps:
    - name: Label as build_passed
      uses: crazymanish/pullrequest-attention-label-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "build_passed"
        AFTER_DAYS: 0
        SKIP_LABELS: ""
  fail_label:
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ failure() }}
    steps:
    - name: Label as build_failed
      uses: crazymanish/pullrequest-attention-label-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "build_failed"
        AFTER_DAYS: 0
        SKIP_LABELS: ""
